### ISSUE TITLE
New CI Build for Jupyter Book - Update GitHub actions

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/contributing-guide#107]
Updating: Jupyter book is now building on circleci and github actions. 

I'm wondering if we need circle CI at all or why we have it?
We will need to update the build to run on actions. open to any help on this item. 

## GitHub actions running on main branch
After reviewing the build i see that the requirements.txt has a pinned version of jupyter book. We definitely want to use the most recent version 

- [x] [remove the pin here](https://github.com/pyOpenSci/contributing-guide/blob/main/requirements.txt#L1)
- [x] [We are also building on python 3.7](https://github.com/pyOpenSci/contributing-guide/blob/main/.github/workflows/book.yml#L20). This likely could be moved to 3.8 atleast if not 3.9 (or 4??)

I suspect doing the above two things will help the build run successfully.

## Now we also want builds to run on other branches to make sure it builds. 
I'm wondering if circle CI allows for a preview of the site?? 

## Tasks
- [x] add link named step to build `jupyter-book build . --builder linkcheck`
- [x] Figure out whether we need circleci involved in t\his built at all
- [x] then either remove it or update it / document
- [x] Document what artifacts.yml does - i think it is linked to circle ci to be able to view the build in an html format
- [x] Make sure actions are up to date in terms of what they are installing (the envt)
- [x] Possibly do we need to clean the branch too it's only building things?  there are likely examples of this build around as lots of other people use jupyterbook. I did look into this it may just replace all files on the branch?
-
NOTES:
* Right now we are building the site from gh-pages branch so the build would push to gh-pages for final deployment from main
* [Here are docs on the suggested build workflow](https://jupyterbook.org/en/stable/publish/gh-pages.html?highlight=Actions)

**Comment by kysolvik** [comment]
Hey @lwasser! I could take this on! I've been looking for a way to get back involved with pyOpenSci and this seems perfect. 

I could do it sometime this week or next, assuming there aren't too many complications.

**Comment by lwasser** [comment]
@kysolvik that would be AMAZING!! thank you. Can I invite you to our slack in case you want to join? you can email me at leah at pyopensci.org if that is of interest.

**Comment by lwasser** [comment]
putting your name on this but of course if you find you are too busy I understand and can remove it!!

**Comment by kysolvik** [comment]
perfect, thanks!!

**Comment by lwasser** [comment]
@kysolvik no rush on this at all but i just wanted to give you a small update for whenever you tackle this. I was able to really easily fix the build part of things but just removing some of the package version pins that we had so that is done so I can update the guide over the next few days. however the artifacts part i'm still a bit confused about. So i'll leave that to you to look at and help us document whenever you have time. Many thanks!

**Comment by kysolvik** [comment]
@lwasser Thanks for the update! Just played around with this for a while (https://github.com/pyOpenSci/contributing-guide/tree/github-ci-build). Here's some notes:

1. I added the link checker to the github actions build, but it looks like there's already an open pull request for that. I removed it from this branch for now. 
2-3. I don't think we need circleci at all, but it does have some nice functionality with regard to artifacts (see below). For now, I removed the config file. If we want to move fully to github actions I think we just need to turn of the circleci webhook. I also updated the README badge from circle ci to github actions. 
4. Circle CI and gh actions both have ways of uploading "artifacts", which are just files generated from the build process that  you might want to check. In our case, that's our book html. For circle ci, there's a nifty interface so you can just click the artifact on the circle ci web page and it opens the html for viewing. Github actions doesn't have this functionality. You have to download the zip, extract it somewhere, then open index.html to view the book. I think this is still useful because otherwise you can't view the book until you merge the changes into main and that gets pushed to gh-pages. Or you can build the book locally to view it. It sounds like a quicker way to view the built html might be added to gh actions at some point: https://github.com/actions/upload-artifact/issues/14
5. Actions looks up to date in terms of installing requirements and nothing is pinned at a version except for the peaceiris/actions-gh-pages, which pushes the changes to the gh-pages branch. I updated that to the most recent version (3.8.0). From their github repo, it sounds like we could setup dependabot to update it automatically. [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-use-the-latest-and-specific-release).
6. Is this about the gh-pages branch? It sounds like the peaceiris/actions-gh-pages action removes all the files in that branch when it pushes from main. [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-keeping-existing-files-keep_files)

I haven't tested the full workflow including pushing from main. If we merge this branch in, that should happen automatically. But if there are hiccups I believe the contributing guide would go down until they're resolved.

**Comment by kysolvik** [comment]
Also, I can add documentation about the CI build to the README once we've decided how to proceed!

**Comment by lwasser** [comment]
hi @kysolvik wow - this is super thorough and incredibly helpful, thank you!!

If you still have time / energy for it, why don't we document this workflow - the ci part in the readme so it's clear how the build works and how you view the artifact files. i think i follow what is happening now. For now i suspect just downloading the file is good enough for us! 

And that's great to know that the build pushes the entire book so it's a clean refresh of the book - i was worried about old pages being in there.

If you are able to document this in the readme, just submit a PR please with the information and we can merge it!

Regarding the link checkers  - that actually still isn't resolved but we have more information now. If you look at that open pr #110  you will see there is a ton of red and id linked to an issue i posted in the jupyter discussions which Chris S. responded to! Essentially the links we've been creating cause the link checker to fail - but fail in a way it shouldnt because the links do work (some may be bad but some are fine). I looked at Chris' response briefly and it looks like we need to create links to a target on the page ... for instance `page.html#header-name-here`  differently with myST.

If you have bandwidth after submitting this readme update and want to tackle the links and link checker i'd love that. if you are too busy i'm super appreciative of the work you've already done. In case you do have bandwidth it's ok if it takes a bit of time for you to get to it as well. 

But let's wrap up this issue first of course! 
Thank you AGAIN!!

**Comment by lwasser** [comment]
one other item, @kysolvik can you please add an actions badge to the readme when this is done so we can see docs are passing/failing?

[oo](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) 

it looks straight forward but if it's not we can skip it! many thanks.

**Comment by kysolvik** [comment]
@lwasser Yes! I can work on documenting the workflow. I added the badge as well: https://github.com/pyOpenSci/contributing-guide/commit/d7daa9710c1bcabe0dcac83fbfd8e44a96aff592. Once I document the workflow I'll open a PR sometime in the next couple days! 

I can help with the links, but it might not be for a couple weeks at least. So if someone else can get to it first they should take it on!

**Comment by lwasser** [comment]
ok no problem!! thank you for doing this @kysolvik and no problem on the link checker. If that issue is still open in a few weeks or more you can have a look if you happen to have time.. but perhaps we will close it by then! much appreciated.

**Comment by lwasser** [comment]
heya @kysolvik just a quick followup. we are gonna keep the circleci build based upon discussion above, correct? and just document it all as it is now? just keeping  @NickleDave in the loop here. So the build will push over to circle ci to create the artifact for viewing without a local build, and the artifacts.yml build brings it over to our repo here for easy access without leaving the repo.

you are just documenting and adding the badge to the readme. 
 Is that a correct summary?

**Comment by kysolvik** [comment]
Hi @lwasser! I don't think we need circleci. Github actions can build the artifact, the only issue is it's not quite as pretty as circle ci, which lets you view the html directly in browser. For now, with github actions you need to download the zip and then open the html. But if we're ok with that, I don't think there's any reason to use both circle ci and github actions. Let me know if I'm missing something though!

I just opened a PR for this change. I need to add the documentation and make some other tweaks, so I'll add to it tomorrow and let you know when it's fully ready. But for now it might help us view the changes more directly: #115

**Comment by kysolvik** [comment]
@lwasser I added documentation about the build to the README. Everything is in PR #115. Let me know what you think! Happy to tweak as needed.

If we want to continue using Circle CI that's an option. I think my vote would be for using one or the other, not both. The only advantage I can see of Circle CI is that it has a prettier way of viewing the built html artifact rather than downloading the site as a zip, but I think something similar might be coming to GitHub Actions sometime soon: https://github.com/actions/upload-artifact/issues/14

**Comment by NickleDave** [comment]
Hi @kysolvik thank you so much for taking time to do this.  

I had asked @lwasser if the plan was to remove Circle CI because in my experience it's quite helpful to be able to point to a single file everyone involved can look at. And the step of having to download is a bit annoying, although of course not the end of the world. I don't mean to make things more complicated after you've already done a lot of work but I would be +1 for keeping Circle CI if we can. Although of course Actions makes life very easy.

Thanks also for sharing that link to https://github.com/actions/upload-artifact/issues/14.  
It's not clear to me when/if that will be resolved and/or if one will be able to view rendered html from an artifact?

Not to make things any more confusing, but another option might be to build on ReadTheDocs as discussed here:
https://github.com/aiidateam/aiida-core/issues/4104
This is what we do for https://github.com/ResearchCodeReviewCommunity/dev-review -- you can give the RtD app access to an org account and then tell RtD to build on all branches and PRs too. Just to be clear: I'm suggest we'd keep the same workflow for actual builds that publish the site in the real world, but add RtD to get around the artifact issue, so we have a live site we can look at for PRs, etc.

Hope I'm not adding noise to the discussion; whatever you all decide will be fine I'm sure.

**Comment by lwasser** [comment]
Thank you for this addition @NickleDave i just want to note that there are two issues that you're addressing in the above comment

1. CI builds... regardless we will want to have a CI build here that facilitates a "view" of what the book looks like. THat would hold true even if we use RTD. so this build and documentation is useful regardless
2. Where we publish. that topic is separate. Do we publish on RTD OR gh-pages.

There are benefits and challenges to both. 
 i'm actually talking with Eric from RTD a bit about this now. The tricky part will be the domain / url piece. 
i think that RTD should be a SEPARATE conversation from this one as it's not straight forward and not related to CI at all. The content can be exactly the same in either location. And we need CI regardless.

**Comment by lwasser** [comment]
Ok let me chime in one more time.. it used to be that finding the build artifact in Circle CI was annoying.. you really had to dig but now... it's really easy to find and is nice.

SEE:
https://app.circleci.com/pipelines/github/pyOpenSci/contributing-guide/292/workflows/6e41e977-025c-458e-a4ad-7bf270618bb1/jobs/352/artifacts

@kysolvik i'm so sorry but i'm leaning with @NickleDave here to leave Circle CI in place as it's a really great way for us to quickly see the build without any download. that might make updates on the run / while traveling etc just that much easier as we can review in browser.

If you've maxed out on time spent Kylen, we can stick to the documentation and update as needed. If you have time to put the circle CI build back, and document that is wonderful. i'm so sorry that our communication wasnt' as clear as it could have been causing your extra work.

**Comment by kysolvik** [comment]
Hi @lwasser and @NickleDave, thanks for the input! I'm super happy to add CircleCI back in, that's easy. Sorry if I misunderstood, based on earlier discussion I thought we had decided that downloading the artifact was good enough for now and so we'd go ahead with GH Actions. But I absolutely agree that CircleCI's functionality for easily viewing the HTML is super handy and @NickleDave makes a good point that while it's an issue on GH Action's radar there doesn't seem to be a timeline or plan for adding that functionality.

Just to make sure I'm on the same page: do we want to use CircleCI only or do we want to use both? If we use both it could look like CircleCI for building and saving the artifact and GitHub Actions for deploying the book. But I'm don't think that's worth it, since we could just use CircleCI can deploy the book and uploading the artifact for easy viewing, like we were in the past. If we're just using CircleCI I think we could just scratch this whole PR and I could add documentation about the CircleCI build and how to view the artifact to the README in a new PR. Let me know if I'm missing something though!

**Comment by kysolvik** [comment]
Hi @lwasser and @NickleDave! Just pinging this, thoughts on how we want to proceed with CircleCI vs. CircleCI + GiHub Actions?

**Comment by lwasser** [comment]
@kysolvik i'm so sorry i missed the message above last week. not sure how i missed it! i'll get back to you in the next day on this. i see what you're saying here.
Github actions is super convenient because the build just lives here 
Circle ci is convenient becuase it provides a html version of the book built to look at in browser.

It's repetitive to have both. but with each by themselves we are giving something up. Let me ping folks on slack to see what they think.

**Comment by lwasser** [comment]
ok @kysolvik i have thought about this more. Again i take full responsibility here for our communication and appreciate your willingness to help here. 

I think having the circle CI online element is useful right now. it will allow me or anyone to review and view a PR without being at a computer. on the go. and avoid needing to download files and open them. I also prefer github actions and hope in the future there is an HTML option. @xmnlab found an action that supposedly does this BUT it's not well maintained and i don't want to use something that isn't maintained :) go figure.

SO let's be redundant (just for now)

please:

1.  put circle CI back (i know... annoying) but let's keep it
2. Let's keep the gh actions artifacts too... i know it's totally redundant ;/ 
3. please document the workflow and just HIGHLIGHT the fact that we have a redundant element and the reason is that artifacts build doesn't yet offer an html preview option. We can then revisit this int he future. perhaps the GH actions build options will be better in the future.
I'm doing this as my hope is - in 6 months to a year we have a solid github action option and can then drop CircleCI without having to lose some useful functionality. 

Does that make sense?
again my apologies for not communicating well with you on this. I hadn't thought the entire thing through. i'm super appreciative of your help here.

**Comment by lwasser** [comment]
awesome!! thanks so much, @kysolvik !!! 🎆

**Comment by lwasser** [comment]
@kysolvik one thing to note that i did today that may change your workflow. To avoid lots of branches here and to encourage PR's i moved most people away from being owners and am setting up teams. i can give you more access to this repo for sure if you need it. or you can fork / pr as i think we'd prefer contributions to happen in the future. just let me know if you need more permissions here!

**Comment by kysolvik** [comment]
@lwasser I can use the fork/pr workflow from now on! Thanks for the heads up.

**Comment by lwasser** [comment]
closing this via #119 thanks again @kysolvik !
